name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Updates every day
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: your-github-username
          template: classic
          base: header, community, repositories, metadata
          config_timezone: America/Toronto
          
          # Isometric Calendar (The 3D blocks)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Languages (Based on your C, Java, Python stack)
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          
          # Coding Habits
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_days: 14
          
          # Music (Manual or Spotify - set to display your favorite)
          plugin_music: yes
          plugin_music_provider: recent
          plugin_music_mode: list
